version: '3.8'

services:
  web:
    build: .
    image: stock-management
    container_name: flask-app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:ashritha@db:5432/fertlizers_db
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: flask-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ashritha
      POSTGRES_DB: fertlizers_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
